### ISSUE TITLE
make docker-build command not found

### ISSUE THREAD

**Issue by ch-stark** [perses/perses-operator#38]
when I follow instructions I get:

make docker-build docker-push IMG=<some-registry>/perses-operator:tag

make: *** No rule to make target 'docker-build'.  Stop.

**Comment by ch-stark** [comment]
moving ahead doing make deploy I get:
containerStatuses:
  - containerID: cri-o://8e65aff7b0cf237c2598df12acecded18c1432a536b94adaf466c6344d1e18b4
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
    imageID: gcr.io/kubebuilder/kube-rbac-proxy@sha256:18f12fc3a0085bbc303cfbd2ad1151127c1c959c4641e36027547b6b66eb4c92
    lastState: {}
    name: kube-rbac-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-12-19T10:32:00Z"
  - image: docker.io/persesdev/perses-operator:v0.1.0
    imageID: ""
    lastState: {}
    name: manager
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: |
          container create failed: time="2024-12-19T10:38:52Z" level=error msg="runc create failed: unable to start container process: exec: \"/manager\": stat /manager: no such file or directory"
        reason: CreateContainerError
  hostIP: 192.168.126.11

**Comment by ch-stark** [comment]
tested with crc locally

**Comment by Nexucis** [comment]
> container create failed: time="2024-12-19T10:38:52Z" level=error msg="runc create failed: unable to start container process: exec: "/manager": stat /manager: no such file or directory"

mmm actually that's because the binary in the perses-operator is `/bin/operator`. Should we change the binary and the place in the docker image @jgbernalp. Or should we just update the file https://github.com/perses/perses-operator/blob/main/config/manager/kustomization.yaml ?

**Comment by jgbernalp** [comment]
Adjusted in #41
